import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter_Tight, Bebas_Neue } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interTight = Inter_Tight({
  variable: "--font-primary",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-secondary",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark ${geistSans.variable} ${geistMono.variable} ${interTight.variable} ${bebasNeue.variable}`}>
      <body
        className="antialiased font-primary"
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
